import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { buildClaimEvidenceLedger, buildPressureOverview, buildRuntimeReviewQueue } from '../src/application/runtime_review_inspector.js';
function tmp(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'review-'));fs.mkdirSync(path.join(d,'local_memory'),{recursive:true});fs.mkdirSync(path.join(d,'shared'),{recursive:true});return d} function jla(f,r){fs.mkdirSync(path.dirname(f),{recursive:true});fs.appendFileSync(f,`${JSON.stringify(r)}\n`)}
test('claim ledger detects unsupported location and correction signals',()=>{const d=tmp();jla(path.join(d,'local_memory','turns.jsonl'),{role:'assistant',text:'케이스타는 서울대입구역 6번 출구 근처에 있습니다.'});jla(path.join(d,'local_memory','turns.jsonl'),{role:'user',text:'아니야. 그 위치 틀렸어. 제대로 확인해야 해.'});const l=buildClaimEvidenceLedger({jobDir:d,persist:true});assert.ok(l.summary.unsupported_count>=1);assert.ok(l.summary.retraction_signal_count>=1);assert.ok(fs.existsSync(path.join(d,'local_memory','claim_ledger_latest.json')))});
test('pressure overview explains topology pressure',()=>{const d=tmp();fs.writeFileSync(path.join(d,'local_memory','memory_topology.json'),JSON.stringify({mode:'structured_single',stress:{score:3.4,reasons:['correction_or_retraction'],stats:{correction_count:2}}}));jla(path.join(d,'local_memory','memory_demand_events.jsonl'),{query:'아까 위치 다시 확인'});const p=buildPressureOverview({jobDir:d,persist:true});assert.equal(p.memory.mode,'structured_single');assert.ok(p.pressure_signals.includes('correction_retraction_pressure'))});
test('review queue combines learned rule and materialization proposals',()=>{const d=tmp();jla(path.join(d,'local_memory','turns.jsonl'),{role:'user',text:'앞으로 파일 만들지 말고 기억만 해줘.'});fs.writeFileSync(path.join(d,'local_memory','memory_materialization_latest.json'),JSON.stringify({candidates:[{domain:'meal_tracking',title:'Meal tracking',recommendation:'create_shadow_table',materialization_score:.7}]}));const q=buildRuntimeReviewQueue({jobDir:d,persist:true});assert.ok(q.summary.proposal_count>=2);assert.ok(q.proposals.some(p=>p.kind==='learned_rule_candidate'));assert.ok(q.proposals.some(p=>p.kind==='materialization_candidate'))});
