import test from 'node:test'
import assert from 'node:assert/strict'

import { createTelegramCommandHandler } from '../src/adapters/telegram/commands.js'

function makeBot(sent) {
  return {
    async sendMessage(chatId, text) {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
  }
}

test('/help shows compact command surface and points to /help more', async () => {
  const sent = []
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
  })

  const handled = await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/help', chatId: 'chat-1', userId: 'user-1' })

  assert.equal(handled, true)
  assert.match(sent[0].text, /\/chat 또는 \/c <message>/)
  assert.match(sent[0].text, /\/brief/)
  assert.match(sent[0].text, /\/continue \[jobId\]/)
  assert.match(sent[0].text, /\/sources/)
  assert.match(sent[0].text, /\/rules/)
  assert.match(sent[0].text, /\/review/)
  assert.doesNotMatch(sent[0].text, /\/agents suggest <목표>/)
  assert.match(sent[0].text, /\/help more/)
  assert.doesNotMatch(sent[0].text, /\/team suggest/)
  assert.doesNotMatch(sent[0].text, /\/outputs/)
})

test('public agent room and legacy artifact aliases return compact guidance', async () => {
  const sent = []
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/agents', chatId: 'chat-1', userId: 'user-1' })
  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/outputs', chatId: 'chat-1', userId: 'user-1' })
  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/sendfile foo.txt', chatId: 'chat-1', userId: 'user-1' })

  assert.match(sent[0].text, /Agent Room/)
  assert.match(sent[0].text, /\/agents suggest/)
  assert.match(sent[1].text, /\/artifacts/)
  assert.match(sent[2].text, /\/send <번호\|path>/)
})


test('/team defaults to a compact summary and details are explicit', async () => {
  const sent = []
  const sessionStore = new Map()
  sessionStore.set('chat-1', {
    team_config: {
      status: 'configured',
      active_team: {
        team_name: 'starter_team',
        composition_mode: 'structured',
        agents: [{ agent_id: 'research_lead' }],
      },
      pending_team: {
        team_name: 'review_team',
        composition_mode: 'freeform',
        agents: [{ agent_id: 'research_lead' }, { agent_id: 'reviewer' }],
      },
    },
  })
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/team', chatId: 'chat-1', userId: 'user-1' })

  assert.ok(sent[0].text.startsWith('Advanced team topology'))
  assert.match(sent[0].text, /active: starter_team/)
  assert.match(sent[0].text, /pending: review_team/)
  assert.match(sent[0].text, /\/agents 권장/)
  assert.doesNotMatch(sent[0].text, /Team commands:/)
})

test('/team details still exposes the fuller state view', async () => {
  const sent = []
  const sessionStore = new Map()
  sessionStore.set('chat-1', {
    team_config: {
      status: 'configured',
      active_team: {
        team_name: 'starter_team',
        composition_mode: 'structured',
        agents: [{ agent_id: 'research_lead' }],
      },
      pending_team: null,
    },
  })
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/team details', chatId: 'chat-1', userId: 'user-1' })

  assert.match(sent[0].text, /Runtime state/)
  assert.match(sent[0].text, /Team commands/)
  assert.match(sent[0].text, /advanced alias/)
})

test('/agents suggest uses the LLM-backed team planner path instead of static room templates', async () => {
  const sent = []
  let plannerCalls = 0
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    createAgentRoomTeamConfiguration: async ({ description }) => {
      plannerCalls += 1
      assert.match(description, /Agent Room for this task/)
      return {
        team_name: 'llm_planned_agent_room',
        composition_mode: 'freeform',
        proposal_mode: 'suggest',
        task_brief: description,
        planner_metadata: {
          planner_type: 'gemini_cli',
          planner_model: 'gemini-3-flash-preview',
          planning_source: 'gemini_cli_team_planner',
          reasoning_summary: ['goal-specific agent room generated by LLM planner'],
        },
        agents: [
          { agent_id: 'goal_researcher', name: 'Goal Researcher', role: 'researcher', provider: 'gemini', model: 'gemini-3-flash-preview', purpose: '목표와 제약을 분석한다' },
          { agent_id: 'workspace_builder', name: 'Workspace Builder', role: 'builder', provider: 'codex', model: 'gpt-5-codex', purpose: '구현 변경을 수행한다' },
          { agent_id: 'risk_reviewer', name: 'Risk Reviewer', role: 'reviewer', provider: 'chatgpt', model: 'gpt-5.4', purpose: '리스크와 승인 경계를 검토한다' },
        ],
        interaction_spec: {
          execution_pattern: 'builder_reviewer_loop',
          final_answer_owner: 'Risk Reviewer',
          handoffs: [
            { from: 'Goal Researcher', to: 'Workspace Builder', payload: 'requirements_and_constraints' },
            { from: 'Workspace Builder', to: 'Risk Reviewer', payload: 'draft_plus_change_summary' },
          ],
        },
      }
    },
  })

  const handled = await handler({
    msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } },
    text: '/agents suggest 국내 주식 리스크 웹앱을 계속 개선하는 방으로 운영해줘',
    chatId: 'chat-1',
    userId: 'user-1',
  })

  assert.equal(handled, true)
  assert.equal(plannerCalls, 1)
  assert.match(sent[0].text, /추천 (AI|Agent) Room 구성입니다/)
  assert.match(sent[0].text, /LLM planner result/)
  assert.match(sent[0].text, /engine: (gemini_cli · gemini-3-flash-preview|team_motif_portfolio)/)
  assert.match(sent[0].text, /(Goal Researcher \(researcher · gemini\/gemini-3-flash-preview\)|Implementation Reviewer \(reviewer · chatgpt\/gpt-5.4\))/)
  assert.doesNotMatch(sent[0].text, /heuristic fallback이 적용되었습니다/)
})

test('/agents export and clone support portable agent packages without private memory copy', async () => {
  const sent = []
  const tmp = await import('node:os').then(({ default: os }) => import('node:fs').then(({ default: fs }) => ({ os, fs })))
  const pathMod = await import('node:path')
  const dir = tmp.fs.mkdtempSync(pathMod.default.join(tmp.os.tmpdir(), 'ddalggak-telegram-pkg-'))
  const oldRegistry = process.env.AGENT_PACKAGE_REGISTRY_PATH
  process.env.AGENT_PACKAGE_REGISTRY_PATH = pathMod.default.join(dir, 'agent_packages.json')

  const backing = new Map()
  const sessionStore = {
    get: (key) => backing.get(String(key)) || {},
    upsert: (key, patcher) => {
      const current = backing.get(String(key)) || {}
      const next = typeof patcher === 'function' ? patcher(current) : { ...current, ...patcher }
      backing.set(String(key), next)
      return next
    },
  }
  sessionStore.upsert('chat-source', () => ({
    agent_room_profile: {
      kind: 'agent_room_profile_v1',
      name: 'Portable Risk Room',
      default_agents: ['planner', 'builder', 'reviewer'],
      current_goal: 'Reusable risk review workflow',
      memory_scope: 'room',
    },
    team_config: {
      active_team: {
        team_name: 'portable_team',
        agents: [{ agent_id: 'reviewer', name: 'Reviewer', role: 'reviewer', provider: 'ollama', model: 'qwen' }],
      },
    },
  }))

  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    resolveLiveJobIdForChat: () => null,
  })

  try {
    await handler({ msg: { chat: { id: 'chat-source' }, from: { id: 'user-1' } }, text: '/agents export', chatId: 'chat-source', userId: 'user-1' })
    assert.match(sent.at(-1).text, /Agent package를 생성/)
    assert.match(sent.at(-1).text, /copies_private_memory=false/)
    const match = sent.at(-1).text.match(/"package_id": "([^"]+)"/)
    assert.ok(match?.[1])

    await handler({ msg: { chat: { id: 'chat-target' }, from: { id: 'user-1' } }, text: `/agents clone ${match[1]}`, chatId: 'chat-target', userId: 'user-1' })
    assert.match(sent.at(-1).text, /source private memory는 복사하지 않았고/)
    const targetSession = sessionStore.get('chat-target')
    assert.equal(targetSession.agent_room_profile.package_id, match[1])
    assert.equal(targetSession.team_config.pending_team.team_name, 'portable_team')
  } finally {
    if (oldRegistry === undefined) delete process.env.AGENT_PACKAGE_REGISTRY_PATH
    else process.env.AGENT_PACKAGE_REGISTRY_PATH = oldRegistry
  }
})

test('advanced help no longer advertises legacy ChatGPT paste commands', async () => {
  const sent = []
  const handler = createTelegramCommandHandler({ bot: makeBot(sent) })
  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/help more', chatId: 'chat-1', userId: 'user-1' })
  assert.doesNotMatch(sent[0].text, /gptapply/)
  assert.doesNotMatch(sent[0].text, /gptprompt/)
  assert.match(sent[0].text, /agents export\|publish-candidate\|packages\|clone/)
})

test('/config and /cfg show effective simplified runtime config', async () => {
  const sent = []
  const oldPreset = process.env.DDALGGAK_RUNTIME_PRESET
  const oldFast = process.env.DDALGGAK_FAST_PROVIDER
  process.env.DDALGGAK_RUNTIME_PRESET = 'local_fast'
  process.env.DDALGGAK_FAST_PROVIDER = 'antigravity'
  try {
    const handler = createTelegramCommandHandler({ bot: makeBot(sent) })
    await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/cfg', chatId: 'chat-1', userId: 'user-1' })
    assert.match(sent[0].text, /runtime config/)
    assert.match(sent[0].text, /preset: local_fast/)
    assert.match(sent[0].text, /fast \/c provider: antigravity/)
  } finally {
    if (oldPreset === undefined) delete process.env.DDALGGAK_RUNTIME_PRESET
    else process.env.DDALGGAK_RUNTIME_PRESET = oldPreset
    if (oldFast === undefined) delete process.env.DDALGGAK_FAST_PROVIDER
    else process.env.DDALGGAK_FAST_PROVIDER = oldFast
  }
})

test('/config doctor returns runtime audit without exposing secret values', async () => {
  const sent = []
  const oldFast = process.env.DDALGGAK_FAST_PROVIDER
  const oldSecret = process.env.DDALGGAK_LOCAL_API_KEY
  process.env.DDALGGAK_FAST_PROVIDER = 'openai_compatible'
  process.env.DDALGGAK_LOCAL_API_KEY = 'unit-test-secret'
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
  })
  try {
    await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/config doctor', chatId: 'chat-1', userId: 'user-1' })
    assert.match(sent[0].text, /config doctor/)
    assert.match(sent[0].text, /Effective runtime/)
    assert.doesNotMatch(sent[0].text, /unit-test-secret/)
  } finally {
    if (oldFast === undefined) delete process.env.DDALGGAK_FAST_PROVIDER
    else process.env.DDALGGAK_FAST_PROVIDER = oldFast
    if (oldSecret === undefined) delete process.env.DDALGGAK_LOCAL_API_KEY
    else process.env.DDALGGAK_LOCAL_API_KEY = oldSecret
  }
})

test('/home and /start show an actionable room dashboard', async () => {
  const sent = []
  const backing = new Map()
  const sessionStore = {
    get: (key) => backing.get(String(key)) || {},
    upsert: (key, patcher) => {
      const current = backing.get(String(key)) || {}
      const next = typeof patcher === 'function' ? patcher(current) : { ...current, ...patcher }
      backing.set(String(key), next)
      return next
    },
  }
  sessionStore.upsert('chat-1', () => ({
    agent_room_profile: {
      name: 'Research Room',
      current_goal: 'usable daily research workflow',
    },
  }))
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/home', chatId: 'chat-1', userId: 'user-1' })
  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/start', chatId: 'chat-1', userId: 'user-1' })

  assert.match(sent[0].text, /AI Room · Continuity Home/)
  assert.match(sent[0].text, /바로 쓰는 명령/)
  assert.match(sent[0].text, /\/room apply <목표>/)
  assert.match(sent[0].text, /\/doctor/)
  assert.match(sent[1].text, /AI Room · Continuity Home/)
})

test('/doctor is a friendly alias for config doctor without exposing secrets', async () => {
  const sent = []
  const oldFast = process.env.DDALGGAK_FAST_PROVIDER
  const oldSecret = process.env.DDALGGAK_LOCAL_API_KEY
  process.env.DDALGGAK_FAST_PROVIDER = 'openai_compatible'
  process.env.DDALGGAK_LOCAL_API_KEY = 'home-dashboard-secret'
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
  })
  try {
    await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/doctor', chatId: 'chat-1', userId: 'user-1' })
    assert.match(sent[0].text, /config doctor/)
    assert.match(sent[0].text, /Effective runtime/)
    assert.doesNotMatch(sent[0].text, /home-dashboard-secret/)
  } finally {
    if (oldFast === undefined) delete process.env.DDALGGAK_FAST_PROVIDER
    else process.env.DDALGGAK_FAST_PROVIDER = oldFast
    if (oldSecret === undefined) delete process.env.DDALGGAK_LOCAL_API_KEY
    else process.env.DDALGGAK_LOCAL_API_KEY = oldSecret
  }
})

test('/inbox summarizes review and correction decision surfaces', async () => {
  const sent = []
  const backing = new Map()
  const sessionStore = {
    get: (key) => backing.get(String(key)) || {},
    upsert: (key, patcher) => {
      const current = backing.get(String(key)) || {}
      const next = typeof patcher === 'function' ? patcher(current) : { ...current, ...patcher }
      backing.set(String(key), next)
      return next
    },
  }
  sessionStore.upsert('chat-1', () => ({
    pending_approval: { reason: 'needs user approval before writing files' },
  }))
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/inbox', chatId: 'chat-1', userId: 'user-1' })

  assert.match(sent[0].text, /DdalGgak Inbox/)
  assert.match(sent[0].text, /job review/)
  assert.match(sent[0].text, /pending approval: needs user approval/)
  assert.match(sent[0].text, /correction proposals: pending=0, accepted=0/)
  assert.match(sent[0].text, /\/correct proposals/)
})
