import test from 'node:test'
import assert from 'node:assert/strict'

import { createTelegramCommandHandler } from '../src/adapters/telegram/commands.js'

function makeBot(sent) {
  return {
    async sendMessage(chatId, text) {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
  }
}

test('/help shows compact command surface and points to /help more', async () => {
  const sent = []
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
  })

  const handled = await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/help', chatId: 'chat-1', userId: 'user-1' })

  assert.equal(handled, true)
  assert.match(sent[0].text, /\/ask <질문>/)
  assert.match(sent[0].text, /\/team <목표>/)
  assert.match(sent[0].text, /\/loop \[--loops n\|staged\] <목표>/)
  assert.match(sent[0].text, /\/review/)
  assert.match(sent[0].text, /\/agents/)
  assert.match(sent[0].text, /\/help more/)
  assert.doesNotMatch(sent[0].text, /\/team suggest/)
  assert.doesNotMatch(sent[0].text, /\/outputs/)
})

test('public agent room and legacy artifact aliases return compact guidance', async () => {
  const sent = []
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/agents', chatId: 'chat-1', userId: 'user-1' })
  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/outputs', chatId: 'chat-1', userId: 'user-1' })
  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/sendfile foo.txt', chatId: 'chat-1', userId: 'user-1' })

  assert.match(sent[0].text, /Agent Room/)
  assert.match(sent[0].text, /\/agents suggest/)
  assert.match(sent[1].text, /\/artifacts/)
  assert.match(sent[2].text, /\/send <번호\|path>/)
})


test('/team defaults to a compact summary and details are explicit', async () => {
  const sent = []
  const sessionStore = new Map()
  sessionStore.set('chat-1', {
    team_config: {
      status: 'configured',
      active_team: {
        team_name: 'starter_team',
        composition_mode: 'structured',
        agents: [{ agent_id: 'research_lead' }],
      },
      pending_team: {
        team_name: 'review_team',
        composition_mode: 'freeform',
        agents: [{ agent_id: 'research_lead' }, { agent_id: 'reviewer' }],
      },
    },
  })
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/team', chatId: 'chat-1', userId: 'user-1' })

  assert.ok(sent[0].text.startsWith('Advanced team topology'))
  assert.match(sent[0].text, /active: starter_team/)
  assert.match(sent[0].text, /pending: review_team/)
  assert.match(sent[0].text, /\/agents 권장/)
  assert.doesNotMatch(sent[0].text, /Team commands:/)
})

test('/team details still exposes the fuller state view', async () => {
  const sent = []
  const sessionStore = new Map()
  sessionStore.set('chat-1', {
    team_config: {
      status: 'configured',
      active_team: {
        team_name: 'starter_team',
        composition_mode: 'structured',
        agents: [{ agent_id: 'research_lead' }],
      },
      pending_team: null,
    },
  })
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/team details', chatId: 'chat-1', userId: 'user-1' })

  assert.match(sent[0].text, /Runtime state/)
  assert.match(sent[0].text, /Team commands/)
  assert.match(sent[0].text, /advanced alias/)
})

test('/agents suggest uses the LLM-backed team planner path instead of static room templates', async () => {
  const sent = []
  let plannerCalls = 0
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    createAgentRoomTeamConfiguration: async ({ description }) => {
      plannerCalls += 1
      assert.match(description, /Agent Room for this task/)
      return {
        team_name: 'llm_planned_agent_room',
        composition_mode: 'freeform',
        proposal_mode: 'suggest',
        task_brief: description,
        planner_metadata: {
          planner_type: 'gemini_cli',
          planner_model: 'gemini-3-flash-preview',
          planning_source: 'gemini_cli_team_planner',
          reasoning_summary: ['goal-specific agent room generated by LLM planner'],
        },
        agents: [
          { agent_id: 'goal_researcher', name: 'Goal Researcher', role: 'researcher', provider: 'gemini', model: 'gemini-3-flash-preview', purpose: '목표와 제약을 분석한다' },
          { agent_id: 'workspace_builder', name: 'Workspace Builder', role: 'builder', provider: 'codex', model: 'gpt-5-codex', purpose: '구현 변경을 수행한다' },
          { agent_id: 'risk_reviewer', name: 'Risk Reviewer', role: 'reviewer', provider: 'chatgpt', model: 'gpt-5.4', purpose: '리스크와 승인 경계를 검토한다' },
        ],
        interaction_spec: {
          execution_pattern: 'builder_reviewer_loop',
          final_answer_owner: 'Risk Reviewer',
          handoffs: [
            { from: 'Goal Researcher', to: 'Workspace Builder', payload: 'requirements_and_constraints' },
            { from: 'Workspace Builder', to: 'Risk Reviewer', payload: 'draft_plus_change_summary' },
          ],
        },
      }
    },
  })

  const handled = await handler({
    msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } },
    text: '/agents suggest 국내 주식 리스크 웹앱을 계속 개선하는 방으로 운영해줘',
    chatId: 'chat-1',
    userId: 'user-1',
  })

  assert.equal(handled, true)
  assert.equal(plannerCalls, 1)
  assert.match(sent[0].text, /추천 Agent Room 구성입니다/)
  assert.match(sent[0].text, /LLM planner result/)
  assert.match(sent[0].text, /engine: gemini_cli · gemini-3-flash-preview/)
  assert.match(sent[0].text, /Goal Researcher \(researcher · gemini\/gemini-3-flash-preview\)/)
  assert.doesNotMatch(sent[0].text, /heuristic fallback이 적용되었습니다/)
})

test('/agents export and clone support portable agent packages without private memory copy', async () => {
  const sent = []
  const tmp = await import('node:os').then(({ default: os }) => import('node:fs').then(({ default: fs }) => ({ os, fs })))
  const pathMod = await import('node:path')
  const dir = tmp.fs.mkdtempSync(pathMod.default.join(tmp.os.tmpdir(), 'ddalggak-telegram-pkg-'))
  const oldRegistry = process.env.AGENT_PACKAGE_REGISTRY_PATH
  process.env.AGENT_PACKAGE_REGISTRY_PATH = pathMod.default.join(dir, 'agent_packages.json')

  const backing = new Map()
  const sessionStore = {
    get: (key) => backing.get(String(key)) || {},
    upsert: (key, patcher) => {
      const current = backing.get(String(key)) || {}
      const next = typeof patcher === 'function' ? patcher(current) : { ...current, ...patcher }
      backing.set(String(key), next)
      return next
    },
  }
  sessionStore.upsert('chat-source', () => ({
    agent_room_profile: {
      kind: 'agent_room_profile_v1',
      name: 'Portable Risk Room',
      default_agents: ['planner', 'builder', 'reviewer'],
      current_goal: 'Reusable risk review workflow',
      memory_scope: 'room',
    },
    team_config: {
      active_team: {
        team_name: 'portable_team',
        agents: [{ agent_id: 'reviewer', name: 'Reviewer', role: 'reviewer', provider: 'ollama', model: 'qwen' }],
      },
    },
  }))

  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    resolveLiveJobIdForChat: () => null,
  })

  try {
    await handler({ msg: { chat: { id: 'chat-source' }, from: { id: 'user-1' } }, text: '/agents export', chatId: 'chat-source', userId: 'user-1' })
    assert.match(sent.at(-1).text, /Agent package를 생성/)
    assert.match(sent.at(-1).text, /copies_private_memory=false/)
    const match = sent.at(-1).text.match(/"package_id": "([^"]+)"/)
    assert.ok(match?.[1])

    await handler({ msg: { chat: { id: 'chat-target' }, from: { id: 'user-1' } }, text: `/agents clone ${match[1]}`, chatId: 'chat-target', userId: 'user-1' })
    assert.match(sent.at(-1).text, /source private memory는 복사하지 않았고/)
    const targetSession = sessionStore.get('chat-target')
    assert.equal(targetSession.agent_room_profile.package_id, match[1])
    assert.equal(targetSession.team_config.pending_team.team_name, 'portable_team')
  } finally {
    if (oldRegistry === undefined) delete process.env.AGENT_PACKAGE_REGISTRY_PATH
    else process.env.AGENT_PACKAGE_REGISTRY_PATH = oldRegistry
  }
})

test('advanced help no longer advertises legacy ChatGPT paste commands', async () => {
  const sent = []
  const handler = createTelegramCommandHandler({ bot: makeBot(sent) })
  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/help more', chatId: 'chat-1', userId: 'user-1' })
  assert.doesNotMatch(sent[0].text, /gptapply/)
  assert.doesNotMatch(sent[0].text, /gptprompt/)
  assert.match(sent[0].text, /agents export\|publish-candidate\|packages\|clone/)
})


test('root /ask, /team, and /loop map to the three task depths', async () => {
  const sent = []
  const handled = []
  const backing = new Map()
  const sessionStore = {
    get: (key) => backing.get(String(key)) || {},
    upsert: (key, patcher) => {
      const current = backing.get(String(key)) || {}
      const next = typeof patcher === 'function' ? patcher(current) : { ...current, ...patcher }
      backing.set(String(key), next)
      return next
    },
  }
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    chatRunManager: {
      async handleIncoming(payload) {
        handled.push(payload)
      },
    },
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { message_id: 1, chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/ask 요약해줘', chatId: 'chat-1', userId: 'user-1' })
  await handler({ msg: { message_id: 2, chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/team 여러 관점으로 검토해줘', chatId: 'chat-1', userId: 'user-1' })
  await handler({ msg: { message_id: 3, chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/loop --loops 3 repo 수정하고 테스트해줘', chatId: 'chat-1', userId: 'user-1' })

  assert.equal(handled.length, 3)
  assert.equal(handled[0].kind, 'task_instant_answer')
  assert.equal(handled[1].kind, 'task_agent_team')
  assert.equal(handled[2].kind, 'task_agent_loop')
  assert.match(handled[2].text, /"loop_budget":3/)
  assert.equal(sessionStore.get('chat-1').pending_task_control.work_mode.work_depth, 'loop')
})

test('/team keeps legacy topology subcommands but freeform text starts a team answer', async () => {
  const sent = []
  const handled = []
  const backing = new Map()
  const sessionStore = {
    get: (key) => backing.get(String(key)) || {},
    upsert: (key, patcher) => {
      const current = backing.get(String(key)) || {}
      const next = typeof patcher === 'function' ? patcher(current) : { ...current, ...patcher }
      backing.set(String(key), next)
      return next
    },
  }
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    chatRunManager: { async handleIncoming(payload) { handled.push(payload) } },
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { message_id: 1, chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/team more', chatId: 'chat-1', userId: 'user-1' })
  assert.equal(handled.length, 0)
  assert.match(sent.at(-1).text, /More team commands/)

  await handler({ msg: { message_id: 2, chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/team 포트폴리오 리스크를 검토해줘', chatId: 'chat-1', userId: 'user-1' })
  assert.equal(handled.length, 1)
  assert.equal(handled[0].kind, 'task_agent_team')
})

test('/ask stays single-agent and does not persist an Agent Room team', async () => {
  const sent = []
  const handled = []
  const backing = new Map()
  const sessionStore = {
    get: (key) => backing.get(String(key)) || {},
    upsert: (key, patcher) => {
      const current = backing.get(String(key)) || {}
      const next = typeof patcher === 'function' ? patcher(current) : { ...current, ...patcher }
      backing.set(String(key), next)
      return next
    },
  }
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    chatRunManager: { async handleIncoming(payload) { handled.push(payload) } },
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { message_id: 1, chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/ask 핵심만 설명해줘', chatId: 'chat-1', userId: 'user-1' })

  assert.equal(handled.length, 1)
  assert.equal(handled[0].kind, 'task_instant_answer')
  assert.equal(handled[0].teamConfig.agents.length, 1)
  assert.match(sent[0].text, /team policy: \/ask does not auto-create or persist/)
  assert.equal(sessionStore.get('chat-1').pending_task_control.team_bootstrap.mode, 'single_agent_ephemeral')
  assert.equal(sessionStore.get('chat-1').team_config?.active_team, undefined)
})

test('/loop without an active team auto-generates a visible loop team bootstrap', async () => {
  const sent = []
  const handled = []
  const backing = new Map()
  const sessionStore = {
    get: (key) => backing.get(String(key)) || {},
    upsert: (key, patcher) => {
      const current = backing.get(String(key)) || {}
      const next = typeof patcher === 'function' ? patcher(current) : { ...current, ...patcher }
      backing.set(String(key), next)
      return next
    },
  }
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    chatRunManager: { async handleIncoming(payload) { handled.push(payload) } },
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { message_id: 1, chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/loop --loops 3 소설 1장을 초안 리뷰 개선 순서로 작성해줘', chatId: 'chat-1', userId: 'user-1' })

  assert.equal(handled.length, 1)
  assert.equal(handled[0].kind, 'task_agent_loop')
  assert.match(sent[0].text, /no active Agent Room was found, so a loop team was generated and applied/)
  assert.match(sent[0].text, /loop confirmation policy: auto-start with visible team summary/)
  assert.match(sent[0].text, /GoC handoff: adjust team, loop budget, memory/)
  assert.equal(sessionStore.get('chat-1').pending_task_control.team_bootstrap.auto_created_team, true)
  assert.ok(sessionStore.get('chat-1').team_config?.active_team)
})
