import test from 'node:test'
import assert from 'node:assert/strict'

import { createTelegramCommandHandler } from '../src/adapters/telegram/commands.js'

function makeBot(sent) {
  return {
    async sendMessage(chatId, text) {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
  }
}

test('/help shows compact command surface and points to /help more', async () => {
  const sent = []
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
  })

  const handled = await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/help', chatId: 'chat-1', userId: 'user-1' })

  assert.equal(handled, true)
  assert.match(sent[0].text, /\/chat <text>/)
  assert.match(sent[0].text, /\/task loop <목표>/)
  assert.match(sent[0].text, /\/agents suggest <목표>/)
  assert.match(sent[0].text, /\/review/)
  assert.match(sent[0].text, /\/help more/)
  assert.doesNotMatch(sent[0].text, /\/team suggest/)
  assert.doesNotMatch(sent[0].text, /\/outputs/)
})

test('public agent room and legacy artifact aliases return compact guidance', async () => {
  const sent = []
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/agents', chatId: 'chat-1', userId: 'user-1' })
  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/outputs', chatId: 'chat-1', userId: 'user-1' })
  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/sendfile foo.txt', chatId: 'chat-1', userId: 'user-1' })

  assert.match(sent[0].text, /Agent Room/)
  assert.match(sent[0].text, /\/agents suggest/)
  assert.match(sent[1].text, /\/artifacts/)
  assert.match(sent[2].text, /\/send <번호\|path>/)
})


test('/team defaults to a compact summary and details are explicit', async () => {
  const sent = []
  const sessionStore = new Map()
  sessionStore.set('chat-1', {
    team_config: {
      status: 'configured',
      active_team: {
        team_name: 'starter_team',
        composition_mode: 'structured',
        agents: [{ agent_id: 'research_lead' }],
      },
      pending_team: {
        team_name: 'review_team',
        composition_mode: 'freeform',
        agents: [{ agent_id: 'research_lead' }, { agent_id: 'reviewer' }],
      },
    },
  })
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/team', chatId: 'chat-1', userId: 'user-1' })

  assert.ok(sent[0].text.startsWith('Advanced team topology'))
  assert.match(sent[0].text, /active: starter_team/)
  assert.match(sent[0].text, /pending: review_team/)
  assert.match(sent[0].text, /\/agents 권장/)
  assert.doesNotMatch(sent[0].text, /Team commands:/)
})

test('/team details still exposes the fuller state view', async () => {
  const sent = []
  const sessionStore = new Map()
  sessionStore.set('chat-1', {
    team_config: {
      status: 'configured',
      active_team: {
        team_name: 'starter_team',
        composition_mode: 'structured',
        agents: [{ agent_id: 'research_lead' }],
      },
      pending_team: null,
    },
  })
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    sendLong: async (_bot, chatId, text) => {
      sent.push({ chatId, text })
      return { message_id: sent.length }
    },
    chatSessionStore: sessionStore,
    resolveLiveJobIdForChat: () => null,
  })

  await handler({ msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } }, text: '/team details', chatId: 'chat-1', userId: 'user-1' })

  assert.match(sent[0].text, /Runtime state/)
  assert.match(sent[0].text, /Team commands/)
  assert.match(sent[0].text, /advanced alias/)
})

test('/agents suggest uses the LLM-backed team planner path instead of static room templates', async () => {
  const sent = []
  let plannerCalls = 0
  const handler = createTelegramCommandHandler({
    bot: makeBot(sent),
    createAgentRoomTeamConfiguration: async ({ description }) => {
      plannerCalls += 1
      assert.match(description, /Agent Room for this task/)
      return {
        team_name: 'llm_planned_agent_room',
        composition_mode: 'freeform',
        proposal_mode: 'suggest',
        task_brief: description,
        planner_metadata: {
          planner_type: 'gemini_cli',
          planner_model: 'gemini-3-flash-preview',
          planning_source: 'gemini_cli_team_planner',
          reasoning_summary: ['goal-specific agent room generated by LLM planner'],
        },
        agents: [
          { agent_id: 'goal_researcher', name: 'Goal Researcher', role: 'researcher', provider: 'gemini', model: 'gemini-3-flash-preview', purpose: '목표와 제약을 분석한다' },
          { agent_id: 'workspace_builder', name: 'Workspace Builder', role: 'builder', provider: 'codex', model: 'gpt-5-codex', purpose: '구현 변경을 수행한다' },
          { agent_id: 'risk_reviewer', name: 'Risk Reviewer', role: 'reviewer', provider: 'chatgpt', model: 'gpt-5.4', purpose: '리스크와 승인 경계를 검토한다' },
        ],
        interaction_spec: {
          execution_pattern: 'builder_reviewer_loop',
          final_answer_owner: 'Risk Reviewer',
          handoffs: [
            { from: 'Goal Researcher', to: 'Workspace Builder', payload: 'requirements_and_constraints' },
            { from: 'Workspace Builder', to: 'Risk Reviewer', payload: 'draft_plus_change_summary' },
          ],
        },
      }
    },
  })

  const handled = await handler({
    msg: { chat: { id: 'chat-1' }, from: { id: 'user-1' } },
    text: '/agents suggest 국내 주식 리스크 웹앱을 계속 개선하는 방으로 운영해줘',
    chatId: 'chat-1',
    userId: 'user-1',
  })

  assert.equal(handled, true)
  assert.equal(plannerCalls, 1)
  assert.match(sent[0].text, /추천 Agent Room 구성입니다/)
  assert.match(sent[0].text, /LLM planner result/)
  assert.match(sent[0].text, /engine: gemini_cli · gemini-3-flash-preview/)
  assert.match(sent[0].text, /Goal Researcher \(researcher · gemini\/gemini-3-flash-preview\)/)
  assert.doesNotMatch(sent[0].text, /heuristic fallback이 적용되었습니다/)
})
